apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
    nodePort: 30829
  selector:
    io.kompose.service: app
  type: LoadBalancer

