apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
      - env:
        - name: CELERY_BROKER
          valueFrom:
            configMapKeyRef:
              key: CELERY_BROKER
              name: broker-env-env
        - name: FLOWER_BROKER
          valueFrom:
            configMapKeyRef:
              key: FLOWER_BROKER
              name: broker-env-env
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_DEFAULT_PASS
              name: broker-env-env
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_DEFAULT_USER
              name: broker-env-env
        image: rabbitmq:3
        name: broker
        ports:
        - containerPort: 5672
        resources: {}
        volumeMounts:
        - name: etc-timezone
          mountPath: /etc/timezone
          readOnly: true
        - name: etc-localtime
          mountPath: /etc/localtime
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: etc-timezone
        hostPath:
          path: /etc/timezone
          type: File
      - name: etc-localtime
        hostPath:
          path: /etc/localtime
          type: File
status: {}

