apiVersion: v1
data:
  CELERY_BROKER: amqp://user:password@10.152.183.2:5672
  FLOWER_BROKER: amqp://user:password@10.152.183.2:5672
  RABBITMQ_DEFAULT_PASS: password
  RABBITMQ_DEFAULT_USER: user
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: broker-env-env
  name: broker-env-env

